// Code generated by hertz generator.

package core_api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _scheduleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createscheduleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createschedulefromoriginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getschedulesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatescheduleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signupMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createschedulesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _stsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendverifycodeMw() []app.HandlerFunc {
	// your code...
	return nil
}
